# Generated by Django 5.0.1 on 2024-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstCarSogang_signuplogin', '0002_alter_normaluser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='studentID',
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='username',
            field=models.IntegerField(unique=True, verbose_name='서강대 학번'),
        ),
    ]
