# Generated by Django 5.0.1 on 2024-02-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstCarSogang_signuplogin', '0004_alter_normaluser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='username',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='서강대 학번'),
        ),
    ]
