# Generated by Django 5.0.1 on 2024-02-04 09:38

import firstCarSogang_signuplogin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstCarSogang_signuplogin', '0006_normaluser_sloworfast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='질문')),
                ('answer', models.CharField(max_length=1000, verbose_name='대답')),
            ],
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=firstCarSogang_signuplogin.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=firstCarSogang_signuplogin.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=firstCarSogang_signuplogin.models.user_directory_path),
        ),
    ]
