# Generated by Django 5.0.1 on 2024-02-08 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterDay1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(unique=True, verbose_name='질문 ID')),
                ('question', models.CharField(max_length=1000, verbose_name='질문1')),
                ('placeholder', models.CharField(max_length=1000)),
                ('multipleChoiceAnswer1', models.CharField(max_length=1000, verbose_name='객관식 답변1')),
                ('multipleChoiceAnswer2', models.CharField(max_length=1000, verbose_name='객관식 답변2')),
                ('multipleChoiceAnswer3', models.CharField(max_length=1000, verbose_name='객관식 답변3')),
                ('multipleChoiceAnswer4', models.CharField(max_length=1000, verbose_name='객관식 답변4')),
                ('multipleChoiceAnswer5', models.CharField(max_length=1000, verbose_name='객관식 답변5')),
                ('answer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='주관식 답변')),
            ],
        ),
        migrations.CreateModel(
            name='Day1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='질문')),
                ('placeholder', models.CharField(max_length=1000)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='대답')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signuplogin_daily_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNumber', models.IntegerField(verbose_name='티켓 번호')),
                ('progressingDay', models.IntegerField(verbose_name='진행중인 날짜')),
                ('isAnswered', models.BooleanField(default=False, verbose_name='답변 여부')),
                ('choose', models.BooleanField(default=False, verbose_name='선택 여부')),
                ('withWhom', models.CharField(max_length=100, verbose_name='대상')),
                ('after_day1_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_related', to='firstCarSogang_tickets.afterday1question')),
                ('day1_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_related', to='firstCarSogang_tickets.day1question')),
                ('users', models.ManyToManyField(related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='여기에 포함된 사용자들')),
            ],
        ),
        migrations.AddField(
            model_name='day1question',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_questions', to='firstCarSogang_tickets.ticket'),
        ),
    ]
