# Generated by Django 5.0.1 on 2024-02-08 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstCarSogang_tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day1question',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='day1question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='after_day1_question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='firstCarSogang_tickets.afterday1question'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='day1_question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstCarSogang_tickets.day1question'),
        ),
    ]
