# Generated by Django 5.0.1 on 2024-02-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstCarSogang_tickets', '0003_afterday1question_answer2_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='after_day1_question',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='day1_question',
        ),
    ]
