# Generated by Django 5.0.1 on 2024-02-13 18:28

from django.conf import settings
from django.db import migrations, models
import django

class Migration(migrations.Migration):

    dependencies = [
        ('firstCarSogang_tickets', '0004_remove_ticket_after_day1_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    ...
operations = [
    migrations.AddField(
        model_name='chatroom',
        name='created_at',
        field=models.DateTimeField(auto_now_add=True),
        preserve_default=False,
    ),
    migrations.AlterField(
        model_name='chatroom',
        name='created_at',
        field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
    ),
]

