# Generated by Django 5.0.1 on 2024-02-18 02:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstCarSogang_signuplogin', '0010_emailverificationotp_userprofile_delete_normaluser'),
        ('firstCarSogang_tickets', '0006_chatroom_created_at_alter_chatroom_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='withWhom',
        ),
        migrations.AddField(
            model_name='ticket',
            name='dayQuestion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(to='firstCarSogang_signuplogin.userprofile', verbose_name='대화 참여자들'),
        ),
        migrations.AlterField(
            model_name='day1question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_question', to='firstCarSogang_signuplogin.userprofile'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='users',
            field=models.ManyToManyField(related_name='tickets', to='firstCarSogang_signuplogin.userprofile', verbose_name='여기에 포함된 사용자들'),
        ),
    ]
