# Generated by Django 5.0.1 on 2024-02-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstCarSogang_signuplogin', '0010_emailverificationotp_userprofile_delete_normaluser'),
        ('firstCarSogang_tickets', '0007_remove_ticket_withwhom_ticket_dayquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='withWhom',
            field=models.IntegerField(blank=True, null=True, verbose_name='상대편 티켓 아이디'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='users',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstCarSogang_signuplogin.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='afterday1question',
            name='comments',
            field=models.ManyToManyField(related_name='after_day1_comments', to='firstCarSogang_tickets.comment'),
        ),
        migrations.AddField(
            model_name='day1question',
            name='comments',
            field=models.ManyToManyField(related_name='day1_comments', to='firstCarSogang_tickets.comment'),
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
        migrations.AddField(
            model_name='ticket',
            name='users',
            field=models.IntegerField(blank=True, null=True, verbose_name='내 티켓 아이디'),
        ),
    ]
